### ISSUE TITLE
Lab 3.1 set up finance management - incomplete instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-800-Business-Central-Functional-Consultant#183]
# Module: 3
#### Step: d

Description of issue
* you need to also delete all the dates after 1st July 2022 if you want the last accounting period to have a start date of 7/1/2023 in task 2.d.

**Comment by Nagakirthi** [comment]
The July 7th 2023 appears to be the last entry given in the instruction.

**Comment by Nagakirthi** [comment]
There is no need to delete. The step says that July 7th 2023 will be the last line and that is taken as first entry when you create next fiscal year if in future.

**Comment by chaast** [comment]
but it also leaves january 1st as the fiscal year start... so that means you have 2 fiscal years starts (one in january and one in july - which does not make any sense. so therefore you have to delete.

**Comment by Nagakirthi** [comment]
Yes. As per the scenario, even though they want to use Microsoft Dynamics 365 Business Central as of January 1st 2022, their new fiscal year does not start until July 1st 2022. Hence we are changing the fiscal year start date to 1st July 2022 and also creating further new fiscal years starting date from 1st july. So that further dates will have fiscal starting year date as 1st july.

**Comment by chaast** [comment]
I am sorry but you are not understanding the problem i have with this lab.... Januar 1st 2023 is still showing as the fiscal year start as well if you follow the lab instructions.. whcih does not make sense

**Comment by Nagakirthi** [comment]
Hi, We have updated the lab guides so that fiscal year is starting from 1st of july and has one date in one fiscal year.

**Comment by chaast** [comment]
that's great. thank you.
